create database if not exists Proyecto;

use Proyecto

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS administrativo (
  ID_ADMINISTRATIVO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO int NOT NULL,
  CONSTRAINT administrativo_ibfk_1 FOREIGN KEY (ID_USUARIO) REFERENCES usuario (ID_USUARIO)
) ;

CREATE TABLE IF NOT EXISTS alumno (
  ID_ALUMNO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO int NOT NULL,
  CONSTRAINT alumno_ibfk_1 FOREIGN KEY (ID_USUARIO) REFERENCES usuario (ID_USUARIO)
) ;

CREATE TABLE IF NOT EXISTS calificacion (
  ID_CALIFICACION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_MATRICULA int NOT NULL,
  ID_CURSO_MATERIA int NOT NULL,
  NOTA decimal(10,0) NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL, 
  CONSTRAINT calificacion_ibfk_1 FOREIGN KEY (ID_MATRICULA) REFERENCES matricula (ID_MATRICULA),
  CONSTRAINT calificacion_ibfk_2 FOREIGN KEY (ID_CURSO_MATERIA) REFERENCES curso_materia (ID_CURSO_MATERIA)
) ;

CREATE TABLE IF NOT EXISTS carrera (
  ID_CARRERA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CARRERA varchar(100) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS curso (
  ID_CURSO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURSO varchar(100) NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL,
  ID_SECCION int NOT NULL,
  ID_CARRERA int NOT NULL,
  ID_GRADO int NOT NULL,
  AO int NOT NULL,
  CONSTRAINT unique_curso UNIQUE(ID_SECCION,ID_CARRERA,ID_GRADO,AO),
  CONSTRAINT curso_ibfk_1 FOREIGN KEY (ID_GRADO) REFERENCES grado (ID_GRADO) ,
  CONSTRAINT curso_ibfk_2 FOREIGN KEY (ID_CARRERA) REFERENCES carrera (ID_CARRERA) ,
  CONSTRAINT curso_ibfk_3 FOREIGN KEY (ID_SECCION) REFERENCES seccion (ID_SECCION) 
) ;

CREATE TABLE IF NOT EXISTS curso_materia (
  ID_CURSO_MATERIA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_HORARIO int NOT NULL,
  ID_MATERIA int NOT NULL,
  ID_CURSO int NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL,
  ID_PROFESOR int NOT NULL,
  CONSTRAINT curso_materia_ibfk_1 FOREIGN KEY (ID_CURSO) REFERENCES curso (ID_CURSO),
  CONSTRAINT curso_materia_ibfk_2 FOREIGN KEY (ID_MATERIA) REFERENCES materia (ID_MATERIA) ,
  CONSTRAINT curso_materia_ibfk_3 FOREIGN KEY (ID_HORARIO) REFERENCES horario (ID_HORARIO) ,
  CONSTRAINT curso_materia_ibfk_4 FOREIGN KEY (ID_PROFESOR) REFERENCES profesor (ID_PROFESOR) 
) ;

CREATE TABLE IF NOT EXISTS grado (
  ID_GRADO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GRADO varchar(100) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS horario (
  ID_HORARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  HORA_INICIO time NOT NULL,
  HORA_FIN time NOT NULL,
  DESCRIPCION varchar(500) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS materia (
  ID_MATERIA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MATERIA varchar(100) NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS matricula (
  ID_MATRICULA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FECHA_INGRESO datetime NOT NULL,
  FECHA_EGRESO datetime NOT NULL,
  AO int NOT NULL,
  ID_ALUMNO int NOT NULL,
  NOTAS varchar(1000) NOT NULL,
  CONSTRAINT matricula_ibfk_1 FOREIGN KEY (ID_ALUMNO) REFERENCES alumno (ID_ALUMNO)
) ;

CREATE TABLE IF NOT EXISTS matricula_curso (
  ID_MATRICULA_CURSO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_MATRICULA int NOT NULL,
  ID_CURSO int NOT NULL,
  NOTAS varchar(1000) NOT NULL,
  CONSTRAINT matricula_curso_ibfk_1 FOREIGN KEY (ID_CURSO) REFERENCES curso (ID_CURSO) ,
  CONSTRAINT matricula_curso_ibfk_2 FOREIGN KEY (ID_MATRICULA) REFERENCES matricula (ID_MATRICULA) 
) ;

CREATE TABLE IF NOT EXISTS pago (
  ID_PAGO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MONTO decimal(10,0) NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL,
  ID_MATRICULA int NOT NULL,
  ID_TIPO_PAGO int NOT NULL,
  FECHA_VENCIMIENTO datetime,
  FECHA_PAGO datetime,
  CONSTRAINT pago_ibfk_1 FOREIGN KEY (ID_TIPO_PAGO) REFERENCES tipo_pago (ID_TIPO_PAGO) ,
  CONSTRAINT pago_ibfk_2 FOREIGN KEY (ID_MATRICULA) REFERENCES matricula (ID_MATRICULA) 
) ;

CREATE TABLE IF NOT EXISTS profesor (
  ID_PROFESOR int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO int NOT NULL,
  CONSTRAINT profesor_ibfk_1 FOREIGN KEY (ID_USUARIO) REFERENCES usuario (ID_USUARIO) 
) ;

CREATE TABLE IF NOT EXISTS seccion (
  ID_SECCION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SECCION varchar(100) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS tipo_pago (
  ID_TIPO_PAGO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TIPO_PAGO varchar(300) NOT NULL,
  DESCRIPCION varchar(1000) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS tipo_usuario (
  ID_TIPO_USUARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TIPO_USUARIO varchar(100) NOT NULL,
  DESCRIPCION varchar(1000) DEFAULT NULL
) ;

CREATE TABLE IF NOT EXISTS usuario (
  ID_USUARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USUARIO varchar(100) NOT NULL,
  NOMBRES varchar(500) NOT NULL,
  APELLIDOS varchar(500) NOT NULL,
  TELEFONO varchar(100) NOT NULL,
  EMAIL varchar(300) NOT NULL,
  ID_TIPO_USUARIO int NOT NULL,
  DOMICILIO varchar(1000) NOT NULL,
  PASSWORD varchar(300) NOT NULL,
  CONSTRAINT usuario_ibfk_1 FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES tipo_usuario (ID_TIPO_USUARIO)
) ;

SET FOREIGN_KEY_CHECKS = 1;